
version: "2"
services:
  web: 
    container_name: docker-compose
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
     container_name: mongo
     image: mongo
     ports:
     - '27017:27017'

